baseDomain: local.narwhal.internal

# repoURL is the Gitea internal URL for apps that source from the GitOps repo
repoURL: http://gitea-http.devtools.svc.cluster.local:3000/gitea-admin/narwhal-gitops.git
