apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ambient-kubelet-probes-ccnp
  namespace: devtools
  annotations:
    narwhal.io/verification-status: "live-verified-2026-09-28-narwhal#235"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: resources
    directory:
      include: "ambient-kubelet-probes-ccnp.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
