apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-admin-ingress-policy
  namespace: devtools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: resources
    directory:
      include: "apisix-admin-ingress-policy.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
