apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost-pod-reaper
  namespace: devtools
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: resources
    directory:
      include: "ghost-pod-reaper.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
