apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-pdb
  namespace: devtools
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: resources
    directory:
      include: "istiod-pdb.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
