apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kisa-compliance
  namespace: devtools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: resources
    directory:
      include: "kisa-compliance.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: devtools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
