apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-rightsizing-rules
  namespace: devtools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: resources
    directory:
      include: "prometheus-rightsizing-rules.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: devtools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
