#!/usr/bin/env python3
"""Generate Velero RBAC from `kubectl api-resources --verbs=list -o wide`."""

import argparse
from collections import defaultdict
from pathlib import Path
import re
import sys

import yaml


DENYLIST = {
    ("", "componentstatuses"): "obsolete cluster health endpoint, not backup data",
    ("", "events"): "short-lived diagnostic records; duplicate events API is excluded too",
    ("events.k8s.io", "events"): "short-lived diagnostic records",
    ("", "nodes"): "live machine inventory is infrastructure state, not namespace backup data",
    ("", "bindings"): "legacy scheduler binding requests are ephemeral control-plane operations",
    ("authentication.k8s.io", "tokenreviews"): "credential validation endpoint exposes authentication decisions",
    ("authorization.k8s.io", "subjectaccessreviews"): "authorization probes expose access decisions",
    ("authorization.k8s.io", "selfsubjectaccessreviews"): "authorization probes expose access decisions",
    ("authorization.k8s.io", "selfsubjectrulesreviews"): "authorization probes expose access decisions",
    ("authorization.k8s.io", "localsubjectaccessreviews"): "authorization probes expose access decisions",
    ("certificates.k8s.io", "certificatesigningrequests"): "cluster-wide signing requests are security-sensitive ephemeral workflow",
    ("metrics.k8s.io", "nodes"): "ephemeral utilization measurements are not backup state",
    ("metrics.k8s.io", "pods"): "ephemeral utilization measurements are not backup state",
    ("coordination.k8s.io", "leases"): "ephemeral leader election and heartbeat state",
}
READ_VERBS = ["get", "list", "watch"]
WRITE_VERBS = ["create", "update", "patch", "delete"]
READ_ONLY_RBAC = {"clusterroles", "clusterrolebindings"}
SPECIAL = {
    ("", "persistentvolumes"),
    ("", "namespaces"),
    ("apiextensions.k8s.io", "customresourcedefinitions"),
}


def parse_snapshot(path: Path) -> dict[tuple[str, str], bool]:
    resources = {}
    for line_number, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = re.match(r"^(\S+)\s+.*\s+(\S+)\s+(true|false)\s+\S+\s+(\S+)(?:\s|$)", line)
        if not match:
            raise ValueError(f"{path}:{line_number}: expected wide api-resources row")
        resource, api_version, namespaced, verbs = match.groups()
        if "/" in resource:
            continue
        api_group = api_version.rsplit("/", 1)[0] if "/" in api_version else ""
        if "list" not in verbs.split(","):
            continue
        key = (api_group, resource)
        resources[key] = namespaced == "true"
    return resources


def rule(api_groups: list[str], names: list[str], verbs: list[str]) -> str:
    return ("  - apiGroups: [" + ", ".join(f'"{group}"' for group in api_groups) + "]\n"
            "    resources: [" + ", ".join(f'"{name}"' for name in names) + "]\n"
            "    verbs: [" + ", ".join(f'"{verb}"' for verb in verbs) + "]\n")


def group_rules(resources: set[tuple[str, str]], verbs: list[str]) -> list[str]:
    by_group = defaultdict(list)
    for group, resource in sorted(resources):
        by_group[group].append(resource)
    return [rule([group], sorted(names), verbs) for group, names in sorted(by_group.items())]


def generate(snapshot: Path) -> str:
    all_resources = parse_snapshot(snapshot)
    # D1: Velero CRDs use one full-access rule; splitting them into ordinary
    # read/write rules would duplicate grants. Cost: group-wide Velero access;
    # escape hatch: replace with explicit Velero verbs after reviewing its API.
    readable = set(all_resources) - set(DENYLIST) - {item for item in all_resources if item[0] == "velero.io"}
    writable = {
        item for item, namespaced in all_resources.items()
        if namespaced or item in SPECIAL
    } - set(DENYLIST) - {item for item in all_resources if item[0] == "velero.io"}
    writable = {
        item for item in writable
        if item[1] not in READ_ONLY_RBAC
        and item != ("apiextensions.k8s.io", "customresourcedefinitions")
    }
    crd = ("apiextensions.k8s.io", "customresourcedefinitions")
    lines = [
        "# Generated by scripts/ops/gen-velero-rbac.py; do not edit by hand.",
        "# READ (get/list/watch) covers every listable API kind except the denylist below.",
        "# Denylist: " + "; ".join(f"{group or 'core'}/{name}: {reason}"
                                   for (group, name), reason in sorted(DENYLIST.items())),
        "# Velero needs cluster RBAC get/list/watch to inspect ServiceAccount bindings.",
        "# D1: Namespaced Roles/RoleBindings stay writable for restore; Kubernetes's",
        "# escalation prevention blocks grants broader than Velero's own permissions.",
        "# ClusterRoles/ClusterRoleBindings remain read-only.",
        "# WRITE (create/update/patch/delete) is limited to namespaced listable kinds,",
        "# PVs and Namespaces. CRDs are create-only; Velero API objects have full access.",
        "# api-resources omits subresources, so rules cannot grant nodes/proxy or pods/exec.",
        "apiVersion: rbac.authorization.k8s.io/v1",
        "kind: ClusterRole",
        "metadata:",
        "  name: velero-server",
        "  labels:",
        "    app.kubernetes.io/managed-by: narwhal",
        "rules:",
    ]
    lines.extend(group_rules(readable, READ_VERBS))
    lines.extend(group_rules(writable, WRITE_VERBS))
    if crd in all_resources:
        lines.append(rule([crd[0]], [crd[1]], ["create"]))
    lines.append(rule(["velero.io"], ["*"], ["*"]))
    lines.extend([
        "---",
        "apiVersion: rbac.authorization.k8s.io/v1",
        "kind: ClusterRoleBinding",
        "metadata:",
        "  name: velero-server-least-privilege",
        "  labels:",
        "    app.kubernetes.io/managed-by: narwhal",
        "roleRef:",
        "  apiGroup: rbac.authorization.k8s.io",
        "  kind: ClusterRole",
        "  name: velero-server",
        "subjects:",
        "  - kind: ServiceAccount",
        "    name: velero-server",
        "    namespace: storage",
        "",
    ])
    return "\n".join(lines)


def readable_inventory(snapshot: Path) -> set[str]:
    resources = parse_snapshot(snapshot)
    readable = set(resources) - set(DENYLIST) - {item for item in resources if item[0] == "velero.io"}
    return {f"{resource}.{group}" if group else resource for group, resource in readable}


def validate_schedules(snapshot: Path, gitops_path: Path, script_path: Path) -> list[str]:
    expected = readable_inventory(snapshot)
    gitops = yaml.safe_load(gitops_path.read_text())["spec"]["source"]["helm"]["valuesObject"]
    script_text = script_path.read_text()
    marker = "cat > /tmp/velero-values.yaml << EOF\n"
    if marker not in script_text:
        return [f"{script_path}: Velero values heredoc missing"]
    script = yaml.safe_load(script_text.split(marker, 1)[1].split("\nEOF", 1)[0])
    problems = []
    for path, values in ((gitops_path, gitops), (script_path, script)):
        configured = values.get("schedules", {}) if isinstance(values, dict) else {}
        if not configured:
            problems.append(f"{path}: no Velero schedules found")
        for name, schedule in configured.items():
            actual_list = schedule.get("template", {}).get("includedResources", [])
            actual = set(actual_list)
            if not actual_list:
                problems.append(f"{path}: schedule {name} lacks includedResources")
            elif len(actual_list) != len(actual) or actual != expected:
                problems.append(f"{path}: schedule {name} differs from generated READ inventory "
                                f"(expected {len(expected)}, got {len(actual)})")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("snapshot", type=Path, help="kubectl api-resources wide output")
    parser.add_argument("-o", "--output", type=Path, help="output YAML path; stdout by default")
    parser.add_argument("--check", action="store_true", help="fail if output differs from generated bytes")
    parser.add_argument("--check-schedules", nargs=2, type=Path, metavar=("GITOPS", "SCRIPT"),
                        help="validate schedule includedResources against generated READ inventory")
    args = parser.parse_args()
    try:
        rendered = generate(args.snapshot)
        schedule_problems = validate_schedules(args.snapshot, *args.check_schedules) if args.check_schedules else []
    except (OSError, ValueError) as exc:
        print(exc, file=sys.stderr)
        return 1
    if schedule_problems:
        print("\n".join(schedule_problems), file=sys.stderr)
        return 1
    if args.check:
        if not args.output or not args.output.exists() or args.output.read_text() != rendered:
            print(f"drift: regenerate {args.output or '<output path required>'}", file=sys.stderr)
            return 1
    elif args.output:
        args.output.write_text(rendered)
    else:
        sys.stdout.write(rendered)
    print(f"READ resources: {len(readable_inventory(args.snapshot))}; "
          f"READ rules: {len(group_rules(set(parse_snapshot(args.snapshot)) - set(DENYLIST), READ_VERBS))}; "
          f"WRITE rules: {len(group_rules({item for item, namespaced in parse_snapshot(args.snapshot).items() if namespaced or item in SPECIAL} - set(DENYLIST) - READ_ONLY_RBAC - {('apiextensions.k8s.io', 'customresourcedefinitions')}, WRITE_VERBS))}; "
          "velero.io full-access rules: 1", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
