apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.18.2
    helm:
      valuesObject:
        expose:
          type: clusterIP
          tls:
            enabled: false
        externalURL: https://harbor.local.narwhal.io
        harborAdminPassword: Harbor12345
        database:
          type: external
          external:
            host: harbor-db-rw
            port: 5432
            username: harbor
            password: harbor-db-password
            coreDatabase: harbor
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: nfs-csi
              size: 50Gi
            jobservice:
              storageClass: nfs-csi
            trivy:
              storageClass: nfs-csi
        redis:
          type: internal
          internal:
            image:
              repository: ghcr.io/dasomel/goharbor/redis-photon
              tag: latest
        trivy:
          enabled: false
        core:
          image:
            repository: ghcr.io/dasomel/goharbor/harbor-core
            tag: latest
          configureUserSettings: |-
            {
              "auth_mode": "oidc_auth",
              "oidc_name": "Keycloak",
              "oidc_endpoint": "https://keycloak.local.narwhal.io/realms/kubernetes",
              "oidc_client_id": "harbor",
              "oidc_client_secret": "harbor-secret",
              "oidc_groups_claim": "groups",
              "oidc_admin_group": "cluster-admins",
              "oidc_scope": "openid,profile,email,groups",
              "oidc_auto_onboard": "true",
              "oidc_verify_cert": "false"
            }
        jobservice:
          image:
            repository: ghcr.io/dasomel/goharbor/harbor-jobservice
            tag: latest
        registry:
          registry:
            image:
              repository: ghcr.io/dasomel/goharbor/registry-photon
              tag: latest
          controller:
            image:
              repository: ghcr.io/dasomel/goharbor/harbor-registryctl
              tag: latest
        portal:
          image:
            repository: ghcr.io/dasomel/goharbor/harbor-portal
            tag: latest
        nginx:
          image:
            repository: ghcr.io/dasomel/goharbor/nginx-photon
            tag: latest
        exporter:
          image:
            repository: ghcr.io/dasomel/goharbor/harbor-exporter
            tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
