apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: devtools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    chart: headlamp
    targetRevision: 0.40.0
    helm:
      valuesObject:
        config:
          oidc:
            clientID: headlamp
            clientSecret: headlamp-secret
            issuerURL: https://keycloak.local.narwhal.io/realms/kubernetes
            scopes: openid,profile,email,groups
        volumes:
          - name: narwhal-ca
            secret:
              secretName: narwhal-ca-cert
        volumeMounts:
          - name: narwhal-ca
            mountPath: /etc/ssl/certs/narwhal-ca.crt
            subPath: ca.crt
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: devtools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
