apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: devtools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 81.5.1
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs-csi
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          assertNoLeakedSecrets: false
          adminPassword: admin
          podLabels:
            istio.io/dataplane-mode: "none"
          persistence:
            enabled: true
            storageClassName: nfs-csi
            size: 5Gi
          sidecar:
            dashboards:
              enabled: true
            datasources:
              enabled: true
          grafana.ini:
            server:
              root_url: https://grafana.local.narwhal.io
            auth.generic_oauth:
              enabled: true
              name: Keycloak
              allow_sign_up: true
              client_id: grafana
              client_secret: grafana-secret
              scopes: openid profile email groups
              auth_url: https://keycloak.local.narwhal.io/realms/kubernetes/protocol/openid-connect/auth
              token_url: https://keycloak.local.narwhal.io/realms/kubernetes/protocol/openid-connect/token
              api_url: https://keycloak.local.narwhal.io/realms/kubernetes/protocol/openid-connect/userinfo
              tls_skip_verify_insecure: true
              role_attribute_path: contains(groups[*], 'cluster-admin') && 'Admin' || contains(groups[*], 'developer') && 'Editor' || 'Viewer'
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs-csi
                  resources:
                    requests:
                      storage: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
