apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: devtools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://seaweedfs.github.io/seaweedfs/helm
    chart: seaweedfs
    targetRevision: 4.34.0
    helm:
      valuesObject:
        global:
          storageClass: nfs-csi
        master:
          enabled: true
          replicas: 1
          storage: 1Gi
          data:
            type: persistentVolumeClaim
            size: 1Gi
            storageClass: nfs-csi
        volume:
          enabled: true
          replicas: 1
          storage: 50Gi
          data:
            type: persistentVolumeClaim
            size: 50Gi
            storageClass: nfs-csi
        filer:
          enabled: true
          replicas: 1
          storage: 5Gi
          data:
            type: persistentVolumeClaim
            size: 5Gi
            storageClass: nfs-csi
          s3:
            enabled: true
            port: 8333
            allowEmptyFolder: true
        s3:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
