apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: devtools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.24.4
    helm:
      valuesObject:
        tempo:
          storage:
            trace:
              backend: s3
              s3:
                endpoint: seaweedfs-s3.storage.svc.cluster.local:8333
                bucket: tempo
                access_key: admin
                secret_key: admin
                insecure: true
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
